### ISSUE TITLE
Suggestion Temporary Session/Excercise Skipping

### ISSUE THREAD

**Issue by Yun5Pc** [WhyAsh5114/MyFit#147]
I've run into a problem where on somedays when my shoulders or knees feel weird or sore i have to push back my whole cycle back a day if i don't want to skip a workout.

For example i had legs yesterday but my knees felt weird and a little painful, so i had to wait out that day but, my back was fresh so i could've trained that instead. My usual split is push legs pull.

So i think it would be beneficial to add a option where you could skip a session temporarily if you run into any problems with joins and stuff.

What I've been doing up till now is as i mentioned above doing the pull workout, writing the reps sets on my notepad and after i do legs fill in the  skipped pull day right after.

**Comment by WhyAsh5114** [comment]
Hmm, I can understand the issue. 
I originally thought that simply having a skip option for workouts would be enough but I didn't consider that you might want to redo that workout immediately soon typically as it would mess up the recovery timespans of the muscle groups. 

Coz if you do Push Pull Legs instead of your typical Push Legs Pull, you'd need to reduce the recovery timespan of Legs by a day and increase the recovery timespan of Pull by a day. I personally wouldn't do this coz of my mild OCD and my back muscles would need to wait a day more unnecessarily, but I understand why some might want to. I'll try to add this in a few days.

**Comment by Yun5Pc** [comment]
i know what you mean i have ocd too lol, but to be precise i run a push legs a(quad focus) pull legs b(hams) i tend to see that my hams and back recover much faster than my quads im still figuring out the balance between volume and recovery it would prolly be better to do both quads and hams at the same time but the overall fatigue is too much because i rely mostly on compound movements im still growing into it so thats probably why ive run into this issue but you know when youre just tired overall you just think even though i couldve hit back today id just push back the whole cycle one day just cuz. i think it would help having a temporary skip option for others as well also it could be just due to a busy day rather than a slight injury and stuff 

also this is totally unrelated but what are you thoughts on like am and pm sessions do you think it would be be beneficial to have that kinda thing or like use push am as (day 1) push pm as (day 2) would like to know your thoughts about it. appreciate all the hardwork and help youre providing bud

**Comment by WhyAsh5114** [comment]
For the AM and PM session, you can just create a 14 day split for now, since algorithm wise it makes no difference. Maybe UI wise, there are ways to improve the case for multiple days in a session. Or just your normal split but add both AM and PM in the same session, the app doesn't care how long it takes for you to complete the workout, it'll save the rep numbers till you hit complete even if you remove it from recent apps.

For the temporary skip part, I was thinking to implement them cycle-wise. One can skip a day in a cycle and that day will be available for redo only for that cycle (before completing the last day of that cycle).

Like in your case, when you skip Legs A temporarily, it'll be available to perform for that cycle again, before you complete Legs B. I will need to do some thorough testing to make sure nothing breaks when you skip workouts and redo them again, so the feature might take some time.

**Comment by Yun5Pc** [comment]
I was thinking the same I've been using am pm both on the same session but as i mentioned above my ocd kicks in lol and it feels like a itch that dosen't go away when u don't complete that workout after you did the first session and in the evening when you complete the session and it shows like 600-700 mins as the workout duration you just wanna punch a wall lol 

about the temporary skipping, that'd be awesome it counts for the fact that you would need to skip for more than a day or two again awesome work bud keep it up

**Comment by Yun5Pc** [comment]
i have run into another issue regarding the skipping 
so today when i tapped the start button on my workout it didn't register so i tapped it again but just before somehow it sent me to the page where you enter your weight or skip so i accidentally skipped my workout
any thoughts regarding this?
i think the reason it didnt register me tapping the start button was probably a error on my end but what do you think about spacing the start button and skip button that would prevent accidents like that happening again 
but now im left with the a skipped workout is there anyway you could maybe help me out and someone else in the future 
what do you think about potentially adding someway to revert the skipped workouts

**Comment by WhyAsh5114** [comment]
You can delete the skipped workout.

In the Workouts page, make sure the filters show skipped workouts as well (they do be default) and then simply delete that workout.

**Comment by Yun5Pc** [comment]
oh awesome i didn't think it would bring it back appreciate the help bud thx
