### ISSUE TITLE
Recommended reps outside of rep range

### ISSUE THREAD

**Issue by Testah2024** [WhyAsh5114/MyFit#93]
I just made a mock-up version to share an example of the issue to replicate it, because I'd deleted the real mesocycle and whatnot that originally had the issue, and went back to using the old V2 as my main app because V3 doesn't seem to work correctly.

Examples:

![image](https://github.com/user-attachments/assets/2ca8e1cb-5bac-44a9-8c15-d6c9c4a1bd8a)
A Belt Squat, the designated rep range is 5-10, for the last set the recommended reps is "3". 

![image](https://github.com/user-attachments/assets/a9bb8411-4798-43a0-b22a-2c96e14fb017)
For Straight Arm Pull Down, the designated rep range is 15-20, but the recommended reps for all sets is "13". The weight also dramatically increased relatively in terms of progression - From 12.5 at 20 reps previous week to 17.5  at 13 reps recommended.

If you need any other information, or me to create any other examples, let me know.

**Comment by WhyAsh5114** [comment]
Okay, thanks for giving me some good examples, I'll add some tests using these numbers to make sure the overload function is actually doing a good job of progressing the numbers.

**Comment by WhyAsh5114** [comment]
Hey @Testah2024, here's the new progression suggestions:

![image](https://github.com/user-attachments/assets/4fed433e-b758-4693-bacb-ebcf5e3ae2ed)


The load of the straight-arm pulldowns hasn't been increased this time because it would make the reps go below the rep range. However, eventually, when increasing the load still allows for the lower rep range limit to be maintained, it will happen:

![image](https://github.com/user-attachments/assets/b9a2b79d-24ae-4711-816e-871c97c42914)

If it's a straight set, the load increase needs to ensure that no set has reps below the rep range, if it's a variable load setType, individual sets are checked and if the load can be increased without going outside the rep range, it will be for that particular set.

This is based on the new Berger formula (#84), and work is in progress in #98, and will be deployed after some remaining tasks. Do let me know if this progression seems satisfactory and if you'd prefer slightly different ways.

**Comment by Testah2024** [comment]
It looks good.
So this would work for V2 set types as well, not only the straight sets?

**Comment by WhyAsh5114** [comment]
Yes, since v2 set types are basically where any set can have any load in any pattern, the load increases would occur individually for each set instead of happening for all sets at once like they would in straight sets.
